version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - /home/mp_11115/sonar/opt/nginx/program.com.tw.key:$YOUR_NGINX_KEY_PATH
      - /home/mp_11115/sonar/opt/nginx/program.com.tw.crt:$YOUR_NGINX_CERT_PATH
      - /home/mp_11115/sonar/opt/nginx/sonarqube.conf:/etc/nginx/conf.d/sonarqube.conf:z
    networks:
      - sonarnet
    restart: always

  database:
    image: postgres:12
    container_name: postgresql
    networks:
      - sonarnet
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqube
    volumes:
      - /home/mp_11115/sonar/opt/postgresql:/var/lib/postgresql:z
      - /home/mp_11115/sonar/opt/postgresql/data:/var/lib/postgresql/data:z

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    hostname: sonarqube
    networks:
      - sonarnet
    depends_on:
      - database
    ports:
      - 9000:9000
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://database:5432/sonarqube
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - /home/mp_11115/sonar/opt/sonarqube/extensions:/opt/sonarqube/extensions:z
      - /home/mp_11115/sonar/opt/sonarqube/logs:/opt/sonarqube/logs:z
      - /home/mp_11115/sonar/opt/sonarqube/data:/opt/sonarqube/data:z

networks:
  sonarnet:
    driver: bridge